networks:
  realworld:
    driver: bridge

volumes:
  valkey-data:
  openobserve-data:
  pg-data:
  iggy-data:
  restate-data:
  grafana-data:

services:
  grafana:
    image: grafana/otel-lgtm:0.13.0
    ports:
      - "3001:3000"
      - "4040:4040"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
    volumes:
      - grafana-data:/data
    networks:
      - realworld

  mailcrab:
    image: marlonb/mailcrab:v1.6.2
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - realworld

  valkey:
    image: valkey/valkey:9
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    networks:
      - realworld

  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: localworld # pragma: allowlist secret
      POSTGRES_DB: realworld
    networks:
      - "realworld"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "realworld", "-U", "postgres"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    volumes:
      - pg-data:/var/lib/postgresql

  # One-shot migration runner (SQL-first).
  # Usage:
  #   docker compose -f infra/local/base.yaml run --rm dbmate up
  dbmate:
    image: amacneil/dbmate:2
    depends_on:
      - postgres
    environment:
      # Connect to the compose postgres service over the internal network.
      DATABASE_URL: postgres://postgres:localworld@postgres:5432/realworld?sslmode=disable
    volumes:
      - ../../crates/data/migrations:/db/migrations:ro
    entrypoint: ["dbmate", "--migrations-dir", "/db/migrations"]
    networks:
      - realworld

  iggy:
    image: apache/iggy:0.6.0
    restart: always
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      IGGY_TCP_ADDRESS: 0.0.0.0:8090
      IGGY_HTTP_ENABLED: "true"
      IGGY_HTTP_ADDRESS: 0.0.0.0:3000
      IGGY_ROOT_USERNAME: iggy
      IGGY_ROOT_PASSWORD: iggy # pragma: allowlist secret
    ports:
      - "8090:8090" # TCP transport for Rust SDK
      - "8080:8080" # QUIC transport (optional)
      - "8092:8092" # WebSocket transport (optional)
      - "3000:3000" # HTTP API + bundled Web UI
    volumes:
      - iggy-data:/local_data
    networks:
      - realworld

  restate:
    image: docker.io/restatedev/restate:1.5.6
    restart: always
    ports:
      - "9070:9070" # HTTP control plane/UI
      - "8081:8081" # ingress endpoint used by the workflow client
      - "9071:9071" # admin gRPC endpoint
    volumes:
      - restate-data:/var/lib/restate
    depends_on:
      - iggy
      - postgres
    networks:
      - realworld
