networks:
  realworld:
    driver: bridge

volumes:
  valkey-data:
  openobserve-data:
  postgres-data:
  iggy-data:
  restate-data:

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.15.3
    restart: always
    ports:
      - "5080:5080"
      - "5081:5081"
    volumes:
      - openobserve-data:/data # we need to use ../ and not ./ because docker-compose is run from the root of the first docker-compose file it finds
    environment:
      ZO_DATA_DIR: /data
      ZO_ROOT_USER_EMAIL: test@po.com
      ZO_ROOT_USER_PASSWORD: test # pragma: allowlist secret
    networks:
      - realworld

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.139.0
    restart: always
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/custom-config.yaml
    command: ["--config=/etc/otelcol-contrib/custom-config.yaml"]
    ports:
      - 1888:1888 # pprof extension
      - 8818:8818 # health_check extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 55679:55679 # zpages extension
    depends_on:
      - openobserve
    networks:
      - realworld

  # unfortunately necessary to manage CORS for the HTTP otel collector
  otel-proxy:
    image: caddy:2.10.2
    restart: always
    ports:
      - 4318:80 # Proxy OTLP HTTP traffic
    depends_on:
      - otel-collector
    volumes:
      - ./otel-proxy:/etc/caddy/Caddyfile
    networks:
      - realworld

  mailcrab:
    image: marlonb/mailcrab:v1.6.2
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - realworld

  valkey:
    image: valkey/valkey:8.1
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    networks:
      - realworld

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: realworld
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld # pragma: allowlist secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - realworld

  iggy:
    image: apache/iggy:latest
    restart: always
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      IGGY_TCP_ADDRESS: 0.0.0.0:8090
      IGGY_HTTP_ENABLED: "true"
      IGGY_HTTP_ADDRESS: 0.0.0.0:3000
      IGGY_ROOT_USERNAME: iggy
      IGGY_ROOT_PASSWORD: iggy # pragma: allowlist secret
    ports:
      - "8090:8090" # TCP transport for Rust SDK
      - "8080:8080" # QUIC transport (optional)
      - "8092:8092" # WebSocket transport (optional)
      - "3000:3000" # HTTP API + bundled Web UI
    volumes:
      - iggy-data:/local_data
    networks:
      - realworld

  restate:
    image: docker.io/restatedev/restate:0.9.0
    restart: always
    command:
      [
        "restate-server",
        "dev-server",
        "--data-dir=/var/lib/restate",
        "--http-port=9070",
        "--ingress-port=8081",
        "--admin-port=9071",
      ]
    ports:
      - "9070:9070" # HTTP control plane/UI
      - "8081:8081" # ingress endpoint used by the workflow client
      - "9071:9071" # admin gRPC endpoint
    volumes:
      - restate-data:/var/lib/restate
    depends_on:
      - iggy
      - postgres
    networks:
      - realworld
